### ISSUE TITLE
Titled and Described Photo

### ISSUE THREAD

**Issue by csikkema** [heitzman/gatsby-episcomedia#6]
When the title for a photo is too long, it wraps to the next line with a very large space.
<img width="1138" alt="screen shot 2019-02-06 at 8 14 22 pm" src="https://user-images.githubusercontent.com/43044729/52386457-d66ea500-2a4b-11e9-939a-c95fe3962562.png">

**Comment by csikkema** [comment]
And description includes HTML tags (I didn't use those in the description)

**Comment by kalebheitzman** [comment]
Fixed with 9dd91dc
