### ISSUE TITLE
Miscategorized Image

### ISSUE THREAD

**Issue by csikkema** [heitzman/gatsby-episcomedia#7]
The only box I checked on this image was for Christmas-- but it shows up under Ordinary Time.
<img width="1188" alt="screen shot 2019-02-06 at 8 25 53 pm" src="https://user-images.githubusercontent.com/43044729/52386906-a1635200-2a4d-11e9-93a7-7bdc8998c376.png">

**Comment by kalebheitzman** [comment]
This should be fixed with the reset of the site.
